let d1 =  new Date()

document.write(d1)
document.write("<br>")
document.write('day number' +d1.getDay()) 
document.write("<br>")

document.write('month number' +d1.getMonth())
document.write("<br>")
document.write('year month', d1.getFullYear())
document.write("<br>")
document.write('hours number',d1.getHours())
document.write("<br>")
document.write('minutes number',d1.getMinutes())
document.write("<br>")
document.write('Seconds number',d1.getSeconds())
